- name: Installing multiple packages
  hosts: node
  become: yes
  tasks:
    - name: Installing packages
      ansible.builtin.package:
        name: "{{ item }}" 
        state: present
  loop:
  - mysql
  - zip
  - nginx