- name: loops 
  hosts: node
  become: yes
  tasks:
    - name: loops
      ansible.builtin.debug:
        msg: " hello every one from {{ item }}"
      loop:
      - INDIA
      - AUSTRALIA
      - PAKISTAN
      - AFGHANISTAN
    