- name: Configuring mongodb
  hosts: mongo
  become: yes
  tasks:
    - name: Copying Repository
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Installing mongodb
      ansible.builtin.dnf:
        name: mongodb-org
        state: present

    - name: Enable mongodb
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes
    
    - name: Replacing listen address
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regex: '0.0.0.0:22'
        replace: '0.0.0.0' 

    - name: Restarting mongodb
      ansible.builtin.service:
        name: mongod
        state: restarted

    
